"""Named constants for tests and e2e assertions."""

from __future__ import annotations

from agents.common.constants import (
    ABOUT_PATH,
    ADMIN_PATH,
    COMMON_MOCK_PORTS,
    CONTACT_PATH,
    DEFAULT_PUBLIC_TARGET,
    DEFAULT_RESEARCH_URL,
    DEFAULT_SCORE,
    DETAILED_FINDINGS_TITLE,
    EXAMPLE_PRIVATE_IP,
    EXAMPLE_RESOLVED_IP,
    EXECUTIVE_SUMMARY_TITLE,
    HTTP_PORT,
    HTTPS_PORT,
    LOGIN_PATH,
    LOOPBACK_IP,
    MAX_SCORE,
    MOCK_RESEARCH_PAGE_TITLE,
    NMAP_TOP_PORTS_SAFE,
    NMAP_TOP_PORTS_STANDARD,
    OSINT_MX_PRIORITY,
    OSINT_SUMMARY_PREFIX,
    OSINT_TIMEOUT_LONG,
    OSINT_TIMEOUT_SHORT,
    OSINT_URL_LIMIT,
    REPORT_TITLE,
    RESEARCH_LINKS_LIMIT,
    RESEARCH_SUMMARY_PREFIX,
    RESEARCH_TEXT_LIMIT,
    SSH_PORT,
    TEXT_SNIPPET_LENGTH,
)

EXPECTED_REPORT_TITLE = REPORT_TITLE
EXPECTED_FINDINGS_SECTION = DETAILED_FINDINGS_TITLE
EXPECTED_OSINT_PREFIX = OSINT_SUMMARY_PREFIX
EXPECTED_RESEARCH_PREFIX = RESEARCH_SUMMARY_PREFIX

# Test-only target/domain constants.
EVIL_DOMAIN = "evil.com"
OTHER_DOMAIN = "other.com"
PRIVATE_IP_192 = "192.168.1.1"
RESEARCH_SUBDOMAIN = f"docs.{DEFAULT_PUBLIC_TARGET}"
WILDCARD_PUBLIC_TARGET = f"*.{DEFAULT_PUBLIC_TARGET}"
EXPECTED_OSINT_SOURCE_COUNT = 10

__all__ = [
    "ABOUT_PATH",
    "ADMIN_PATH",
    "COMMON_MOCK_PORTS",
    "CONTACT_PATH",
    "DEFAULT_PUBLIC_TARGET",
    "DEFAULT_RESEARCH_URL",
    "DEFAULT_SCORE",
    "DETAILED_FINDINGS_TITLE",
    "EXAMPLE_PRIVATE_IP",
    "EXAMPLE_RESOLVED_IP",
    "EXECUTIVE_SUMMARY_TITLE",
    "EVIL_DOMAIN",
    "EXPECTED_FINDINGS_SECTION",
    "EXPECTED_OSINT_PREFIX",
    "EXPECTED_OSINT_SOURCE_COUNT",
    "EXPECTED_REPORT_TITLE",
    "EXPECTED_RESEARCH_PREFIX",
    "HTTP_PORT",
    "HTTPS_PORT",
    "OTHER_DOMAIN",
    "PRIVATE_IP_192",
    "RESEARCH_SUBDOMAIN",
    "WILDCARD_PUBLIC_TARGET",
    "LOGIN_PATH",
    "LOOPBACK_IP",
    "MAX_SCORE",
    "MOCK_RESEARCH_PAGE_TITLE",
    "NMAP_TOP_PORTS_SAFE",
    "NMAP_TOP_PORTS_STANDARD",
    "OSINT_MX_PRIORITY",
    "OSINT_SUMMARY_PREFIX",
    "OSINT_TIMEOUT_LONG",
    "OSINT_TIMEOUT_SHORT",
    "OSINT_URL_LIMIT",
    "REPORT_TITLE",
    "RESEARCH_LINKS_LIMIT",
    "RESEARCH_SUMMARY_PREFIX",
    "RESEARCH_TEXT_LIMIT",
    "SSH_PORT",
    "TEXT_SNIPPET_LENGTH",
]
