#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the penetra repo.
# Prepares the Python LangGraph backend and the React Router frontend so both
# dev servers (declared as terminals in environment.json) can start.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# The base image ships Python 3.12 but not the stdlib venv module (ensurepip),
# which `python3 -m venv` needs. Install it once; apt is a no-op when present.
if ! python3 -c "import ensurepip" >/dev/null 2>&1; then
  sudo apt-get update
  sudo apt-get install -y --no-install-recommends python3.12-venv
fi

# --- Backend: LangGraph agent API server ---
cd "$ROOT/backend"
[ -d .venv ] || python3 -m venv .venv
.venv/bin/pip install -U pip
.venv/bin/pip install -e ".[dev]"
# Chromium is used by the research browser tool and the PDF reporter.
.venv/bin/playwright install --with-deps chromium

# First-run dev config. Offline-safe: every scanner runs in mock mode, so no
# Docker daemon, no outbound network, and no third-party API keys are required.
# Add OPENROUTER_API_KEY as an environment secret to enable the LLM chat, and
# TARGET_USERNAME / TARGET_PASSWORD to let the scanner authenticate to the demo
# target. Never overwrite an existing (developer-owned) .env.
if [ ! -f .env ]; then
  cat > .env <<'ENV'
# Local Cloud Agent dev config (auto-generated by .cursor/install.sh).
LOG_LEVEL=INFO

# Authorized (demo) target used by the pentest pipeline.
TARGET_HOST=clinic.72-61-136-120.nip.io
TARGET_URL=https://clinic.72-61-136-120.nip.io

# Centralized scope policy.
ALLOWED_TARGETS=["clinic.72-61-136-120.nip.io"]
RESEARCH_ALLOWED_TARGETS=["clinic.72-61-136-120.nip.io"]
NMAP_ALLOWED_TARGETS=["clinic.72-61-136-120.nip.io"]
EXPLOIT_ALLOWED_TARGETS=["clinic.72-61-136-120.nip.io"]
BLOCK_PRIVATE_IPS=true

# Scanners in mock mode (no Docker / network needed for local dev).
NMAP_MOCK=true
NMAP_USE_DOCKER=false
PYTHON_USE_DOCKER=false
RESEARCH_MOCK=true
OSINT_MOCK=true

# Exploitation simulation stays disabled.
EXPLOIT_EXECUTE=false
EXPLOIT_SANDBOX=true

# OpenRouter LLM (leave key unset here; provide it via an environment secret).
OPENROUTER_MODEL=tencent/hy3:free
OPENROUTER_API_BASE=https://openrouter.ai/api/v1

# E2E test knobs (used by the e2e-marked pytest suite).
E2E_SCOPE=["clinic.72-61-136-120.nip.io"]
E2E_DENIED_TARGET=10.0.0.1
RESEARCH_URL=https://clinic.72-61-136-120.nip.io
OSINT_TARGET=clinic.72-61-136-120.nip.io
ENV
fi

# --- Frontend: React Router 7 SSR app ---
cd "$ROOT/frontend"
pnpm install --frozen-lockfile

echo "penetra install complete."
